#!/bin/bash

DOMAIN="$1"
if [[ "$2" == "" ]]
then
    START_URL="http://$DOMAIN"
else
    START_URL="$2"
fi

PARAMS="--domains=$DOMAIN,www.$DOMAIN,$SAVESITES_DOMAINS $3 $4 $5 $6 $7 $8 $9 $START_URL"
SUBDIR="backup_$DOMAIN"
if [ -e "$SUBDIR" ]; then
    echo "$SUBDIR already exists (completely downloaded, but when?)"
elif [ -e "$SUBDIR.zip" ]; then
    echo "$SUBDIR already exists (completely downloaded and zipped)"
    exit
elif [ -e "~$SUBDIR" ]; then
    echo "~$SUBDIR already exists (incompletely downloaded), you should remove it"
    exit 1
else
    mkdir "~$SUBDIR"
    cd "~$SUBDIR"
    dig +trace $DOMAIN | tee -a dig.log
    dig +trace $DOMAIN ANY | tee -a dig.log
    dig +trace $DOMAIN TXT | tee -a dig.log
    whois $DOMAIN | tee -a whois.log
    echo "wget ... $PARAMS" | tee -a wget.log
    wget --continue --recursive --follow-ftp --retr-symlinks --restrict-file-names=windows --convert-links -e robots=off -E --tries=5 --mirror -K -p --no-check-certificate --user-agent="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0" --timestamping -H $PARAMS 2>&1 | tee -a wget.log
    if [ $? -eq 0 ]
    then
	#du -h $DOMAIN 2>&1 | tee -a wget.log
	#du -h www.$DOMAIN 2>&1 | tee -a wget.log
	wget --timeout=10 --output-document=informer.html https://website.informer.com/$DOMAIN 2>&1 | tee -a wget.log
	wget --timeout=10 --output-document=emails.html https://website.informer.com/$DOMAIN/emails 2>&1 | tee -a wget.log
	wget --timeout=10 --output-document=scorecard.html https://www.mywot.com/en/scorecard/$DOMAIN 2>&1 | tee -a wget.log
	du -h . 2>&1 | tee -a wget.log
	echo -n "Counting... "
	FILESCOUNT=$(find . | wc -l)
	echo "$FILESCOUNT files" | tee -a wget.log
	cd ..
	mv "~$SUBDIR" "$SUBDIR"
	echo "$SUBDIR downloaded successfully (perhaps)"
    else
	cd ..
	echo "~$SUBDIR downloaded partially (check if sufficient disk space)"
	exit 1
    fi
fi

ZIPFILE="$SUBDIR.zip"
if [ -d "$SUBDIR" ]; then
	if [ ! -e "$ZIPFILE" ]; then
		zip -1 -T -r $ZIPFILE $SUBDIR
		if [ $? -eq 0 ]; then
			if [ ! -e "~$SUBDIR" ]; then
				echo -n "Deleting ~$SUBDIR..."
				mv "$SUBDIR" "~$SUBDIR"
				rm -r "~$SUBDIR"
				if [ $? -eq 0 ]; then
				    echo " Done"
				else
				    echo ""
				    exit 1
				fi
			fi
		fi
	fi
fi

type -P miceweb &>/dev/null && ISINST=1 || ISINST=0
if [ $ISINST -eq 1 ]
then
    miceweb save "$START_URL"
else
    >&2 echo "Error: miceweb is not installed (seeing https://github.com/Robotizing/MiceWeb/)"
fi
