#!/bin/bash

if [[ "$SAVESITE_MAXSNAPSHOTPAGES" == "" ]]
then
    # increase it if need to backup huge sites, or better execute 'export SAVESITE_MAXSNAPSHOTPAGES=...' before running the script
    MAXSP=100000
else
    MAXSP="$SAVESITE_MAXSNAPSHOTPAGES"
fi

DOMAIN="$1"

type -P wayback_machine_downloader &>/dev/null && ISINST=1 || ISINST=0

if [ $ISINST -eq 0 ]
then
    echo "Install Ruby, then execute 'sudo gem install wayback_machine_downloader'"
    echo "See also https://linuxnightly.com/how-to-download-a-website-from-the-wayback-machine"
    echo ""
    exit 127
fi

SUBDIR="archived_$DOMAIN"
if [ -e "$SUBDIR" ]; then
    echo "$SUBDIR already exists (completely downloaded, but when?)"
elif [ -e "$SUBDIR.zip" ]; then
    echo "$SUBDIR already exists (completely downloaded and zipped)"
    exit
#elif [ -e "~$SUBDIR" ]; then
#    echo "~$SUBDIR already exist (incompletely downloaded), you should remove it"
#    exit 1
else
    wayback_machine_downloader -s -p $MAXSP -c 1 -d ./~$SUBDIR http://$DOMAIN
    if [ $? -eq 0 ]
    then
	if [ -d "~$SUBDIR" ]; then
	    du -h ./~$SUBDIR
	    mv "~$SUBDIR" "$SUBDIR"
	    echo "$SUBDIR downloaded successfully (perhaps)"
	else
	    exit
	fi
    else
	echo "~$SUBDIR not downloaded"
	exit 1
    fi
fi

ZIPFILE="$SUBDIR.zip"
if [ -d "$SUBDIR" ]; then
	if [ ! -e "$ZIPFILE" ]; then
		zip -1 -T -r $ZIPFILE $SUBDIR
		if [ $? -eq 0 ]; then
			if [ ! -e "~$SUBDIR" ]; then
				echo -n "Deleting ~$SUBDIR..."
				mv "$SUBDIR" "~$SUBDIR"
				rm -r "~$SUBDIR"
				if [ $? -eq 0 ]; then
				    echo " Done"
				else
				    echo ""
				    exit 1
				fi
			fi
		fi
	fi
fi
